/**
 * Scaffolding: a new afi.analysis-plugin.v1 manifest skeleton plus an
 * implementation-contract TypeScript stub, generated from category + id.
 * The emitted manifest is schema-valid; the stub is the declarative
 * implementation contract the consuming runtime's BUILD-TIME plugin registry
 * binds to (no filesystem paths, no dynamic loading — see the contract's
 * x-afiConstraints.buildTimeBinding).
 */
import type { AnalysisPluginManifest } from './generated/analysis-plugin.js';

export type PluginCategory = AnalysisPluginManifest['category'];

export const CATEGORIES: readonly PluginCategory[] = [
  'technical',
  'pattern',
  'sentiment',
  'news',
  'aiMl',
  'merge',
  'scorer',
];

const ANALYSIS_CATEGORIES: readonly PluginCategory[] = ['technical', 'pattern', 'sentiment', 'news', 'aiMl'];

export function scaffoldPluginManifest(input: {
  pluginId: string;
  category: PluginCategory;
}): AnalysisPluginManifest {
  const { pluginId, category } = input;
  if (!/^[a-z0-9-]+$/.test(pluginId)) {
    throw new Error(`pluginId '${pluginId}' must match ^[a-z0-9-]+$`);
  }
  if (!CATEGORIES.includes(category)) {
    throw new Error(`category '${category}' must be one of ${CATEGORIES.join(', ')}`);
  }
  return {
    schema: 'afi.analysis-plugin.v1',
    pluginId,
    pluginVersion: '0.1.0',
    implementationVersion: '0.1.0',
    category,
    description: `SKELETON — declare what the '${pluginId}' ${category} plugin does, then edit every field below.`,
    inputSchemaRef: 'afi.usignal.v1.1',
    outputSchemaRef: `afi.enrichment.${category}.v1`,
    deterministic: true,
    capabilities: [],
    paramsSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {},
    },
    multiInstance: ANALYSIS_CATEGORIES.includes(category),
    mayFeedScorer: category !== 'scorer',
  };
}

function pascalCase(id: string): string {
  return id
    .split('-')
    .filter(Boolean)
    .map((s) => s[0].toUpperCase() + s.slice(1))
    .join('');
}

/** TypeScript implementation-contract stub for a scaffolded plugin. */
export function scaffoldPluginContract(input: { pluginId: string; category: PluginCategory }): string {
  const name = pascalCase(input.pluginId);
  return `/**
 * Implementation contract stub for the '${input.pluginId}' ${input.category} plugin
 * (afi.analysis-plugin.v1). Generated by \`afi-factory plugin scaffold\`.
 *
 * The consuming runtime binds this contract in its BUILD-TIME plugin
 * registry keyed by pluginId+pluginVersion — no filesystem paths, no dynamic
 * imports (contract x-afiConstraints.buildTimeBinding). Implementations must
 * honour the manifest's declarations: determinism, capabilities, failure
 * policies, and the paramsSchema that validates \`params\`.
 */

/** Input payload — must conform to the manifest's inputSchemaRef. */
export interface ${name}Input {
  // TODO: shape of the validated input this plugin consumes.
  [key: string]: unknown;
}

/** Output payload — must conform to the manifest's outputSchemaRef. */
export interface ${name}Output {
  // TODO: shape of the enrichment this plugin produces.
  [key: string]: unknown;
}

/** Node config — must validate against the manifest's paramsSchema. */
export interface ${name}Params {
  // TODO: mirror the paramsSchema fields here.
}

export interface ${name}Plugin {
  readonly pluginId: '${input.pluginId}';
  readonly pluginVersion: string;
  readonly category: '${input.category}';

  /**
   * Executes one node invocation. MUST be a pure function of
   * (input, params) when the manifest declares deterministic:true.
   * Failures throw — the runtime applies the node's declared failure policy;
   * there is no demo/mock/synthetic fallback (D-FCP-8).
   */
  run(input: ${name}Input, params: ${name}Params): Promise<${name}Output>;
}
`;
}
